//---ACTORS--- complete the links below with valid values from the actual database


### Get all actors 
GET http://localhost:5000/actors/ HTTP/1.1

### Get by id -- example: http://localhost:5000/actors/68ce23b2fb19f10ed2099214
GET http://localhost:5000/actors/ HTTP/1.1



### Post actor
POST http://localhost:5000/actors/ HTTP/1.1
Content-Type: application/json

    {
        "fistName": "jamie lee",
        "lasName": "curtis", 
        "birthdate": "11/22/1958", //MM/DD/YYYY
        "nationality": "american"
    }

### Update actor -- complete the link with a valid ID and another example info
PUT http://localhost:5000/actors/ HTTP/1.1
Content-Type: application/json

    {
        "fistName": "jamie lee",
        "lasName": "curtis", 
        "birthdate": "11/22/1958", //MM/DD/YYYY
        "nationality": "american"
    }

### Delete actor -- complete the link with a valid ID
DELETE http://localhost:5000/actors/ HTTP/1.1