//---ACTORS--- complete the links below with valid values from the actual database


### Get all actors 
GET http://localhost:5000/actors/ HTTP/1.1

### Get by id -- example: http://localhost:5000/actors/68ce23b2fb19f10ed2099214
GET http://localhost:5000/actors/ HTTP/1.1



### Post actor
POST http://localhost:5000/actors/ HTTP/1.1
Content-Type: application/json

    {
        "name": "Leonardo DiCaprio",
        "birthYear": 1974,
        "nationality": "American",
        "knownFor": ["Inception", "Titanic", "The Revenant"],
        "awards": ["Academy Award", "Golden Globe Award"]
    }

### Update actor -- complete the link with a valid ID and another example info
PUT http://localhost:5000/actors/ HTTP/1.1
Content-Type: application/json

    {
        "name": "Leonardo DiCaprio",
        "birthYear": 1974,
        "nationality": "American",
        "knownFor": ["Inception", "Titanic", "The Revenant"],
        "awards": ["Academy Award", "Golden Globe Award"]
    }

### Delete actor -- complete the link with a valid ID
DELETE http://localhost:5000/actors/ HTTP/1.1