//---MOVIES--- complete the links below with valid values from the actual database

### Get all movies 
GET http://localhost:5000/movies/ HTTP/1.1

### Get by id -- example: http://localhost:5000/movies/68ce23b2fb19f10ed2099214
GET http://localhost:5000/movies/68e18dc368cb9f62e376470d HTTP/1.1

### Get by title -- example: http://localhost:5000/movies/findByTitle/Flipped == must be in Senctence case
GET http://localhost:5000/movies/findByTitle/Inception HTTP/1.1

### Get by director -- example: http://localhost:5000/movies/findByDirector/Rob Reiner -- (the '+' replaces blank spaces)
GET http://localhost:5000/movies/findByDirector/Damien Chazelle HTTP/1.1

### Get by one of the actors -- example: http://localhost:5000/movies/findByActor/Jamie Lee Curtis -- (the '+' replaces blank spaces)
GET http://localhost:5000/movies/findByActor/Chadwick Boseman HTTP/1.1

### Get by one of the genres -- example: http://localhost:5000/movies/findByGenre/Science Fiction -- (the '+' replaces blank spaces)
GET http://localhost:5000/movies/findByGenre/Action HTTP/1.1

//what I know is that: Jamie Lee != jamie lee (I am not sure how to make it case-inssensitive yet)
//I will suggest entering making all the values from the database lower case

### Post movie
POST http://localhost:5000/movies/ HTTP/1.1
Content-Type: application/json

    {
        "title":"flipped",
        "releaseYear":2010,
        "director":"rob reiner",
        "actors":["madeline carroll", "callan mcauliffle"],
        "producer":"rob reiner",
        "country":"usa",
        "genres":["romance", "youth", "fantasy"],
        "category": "comedy-drama"  
    }

### Update movie -- complete the link with a valid ID and another example info
PUT http://localhost:5000/movies/ HTTP/1.1
Content-Type: application/json

    {
        "title":"flipped",
        "releaseYear":2010,
        "director":"rob reiner",
        "actors":["madeline carroll", "callan mcauliffle"],
        "producer":"rob reiner",
        "country":"usa",
        "genres":["romance", "youth", "fantasy"],
        "category": "comedy-drama"  
    }

### Delete movie -- complete the link with a valid ID
DELETE http://localhost:5000/movies/ HTTP/1.1